[package]
name = "uwebr-core"
description = "Framework core: state, lifecycle, routing for uwebr"
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true

[dev-dependencies]
uwebr-macro = { path = "../uwebr-macro" }
