[package]
name = "uwebr-cli"
description = "CLI tool for uwebr projects"
license.workspace = true
version.workspace = true
edition.workspace = true

[[bin]]
name = "uwebr"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
uwebr-js = { workspace = true }
uwebr-html = { workspace = true }
uwebr-css = { workspace = true }
uwebr-core = { workspace = true }
uwebr-render = { workspace = true }
uwebr-dynlib = { workspace = true }
uwebr-app = { workspace = true }
tempfile.workspace = true
notify = "7"
walkdir = "2"
pollster = "0.4"
winit = "0.30"

[dev-dependencies]
uwebr-core = { workspace = true }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "hot_reload_bench"
harness = false
