[package]
name = "uwebr-cli"
description = "CLI tool for uwebr projects"
license.workspace = true
version.workspace = true
edition.workspace = true

[[bin]]
name = "uwebr"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
uwebr-js = { workspace = true }
uwebr-html = { workspace = true }
uwebr-css = { workspace = true }
uwebr-render = { workspace = true }
notify = "7"
walkdir = "2"

[dev-dependencies]
tempfile.workspace = true
uwebr-core = { workspace = true }
