[package]
name = "uwebr-dynlib"
description = "Shared library compiler for uwebr hot reload"
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
tempfile.workspace = true
log = "0.4"
uwebr-core = { workspace = true }
uwebr-transpiler = { workspace = true }
libloading = "0.8"

[dev-dependencies]
