//! .uwebr → Rust transpiler.
//!
//! `.uwebr` dosyalarındaki HTML + `<script>` + `<style>` bloklarını
//! derlenebilir Rust koduna dönüştürür.

use anyhow::Result;
use std::fs;
use std::path::Path;
use uwebr_html::ast::{HtmlAttributeValue, HtmlNode};
use uwebr_html::directives::expand_directives;
use uwebr_html::parser::parse_html;
use uwebr_js::ScriptResult;

/// Transpile a .uwebr file to Rust source code
pub fn transpile_file(path: &Path) -> Result<String> {
    let content = fs::read_to_string(path)?;
    let file_name = path
        .file_stem()
        .and_then(|n| n.to_str())
        .unwrap_or("Component");
    transpile(&content, file_name)
}

/// Everything the element codegen needs to know about the `<script>` block.
///
/// Without this, `{count}` in the template and `count` in the script are
/// unrelated: the template would emit a bare `count` identifier that is not in
/// scope, and `on:click={increment}` would be dropped as a plain string.
#[derive(Debug, Default, Clone)]
struct ScriptBindings {
    /// Top-level state names, e.g. `count`.
    states: Vec<String>,
    /// Top-level function names, e.g. `increment`.
    functions: Vec<String>,
}

impl ScriptBindings {
    fn from_result(result: &ScriptResult) -> Self {
        Self {
            states: result.states.iter().map(|s| s.name.clone()).collect(),
            functions: result.functions.clone(),
        }
    }

    fn is_state(&self, name: &str) -> bool {
        self.states.iter().any(|s| s == name)
    }

    fn is_function(&self, name: &str) -> bool {
        self.functions.iter().any(|f| f == name)
    }

    /// Rewrite state reads in a template expression into getter calls.
    ///
    /// `{count}` → `__state_count()`, `{count + 1}` → `__state_count() + 1`.
    fn rewrite_expr(&self, expr: &str) -> String {
        if self.states.is_empty() {
            return expr.to_string();
        }

        let mut out = String::with_capacity(expr.len());
        let mut ident = String::new();

        let flush = |ident: &mut String, out: &mut String| {
            if ident.is_empty() {
                return;
            }
            if self.is_state(ident) {
                out.push_str(&format!("__state_{}()", ident));
            } else {
                out.push_str(ident);
            }
            ident.clear();
        };

        for ch in expr.chars() {
            if ch.is_alphanumeric() || ch == '_' {
                ident.push(ch);
            } else {
                flush(&mut ident, &mut out);
                out.push(ch);
            }
        }
        flush(&mut ident, &mut out);

        out
    }
}

/// Transpile .uwebr content to Rust source code
pub fn transpile(content: &str, component_name: &str) -> Result<String> {
    // Extract <style> blocks
    let css = extract_tag(content, "style");
    // Extract <script> blocks
    let script = extract_tag(content, "script");
    // Get HTML (everything except style and script)
    let html = extract_html(content);

    // Parse HTML
    let mut root = parse_html(&html)?;

    // Expand template directives ({#each}, {#if}, etc.)
    expand_directives(&mut root);

    // Transpile the script first: the template needs its state/function names.
    let script_result = if script.is_empty() {
        None
    } else {
        match uwebr_js::transpile_script(&script) {
            Ok(r) => Some(r),
            Err(e) => {
                // Keep going: a broken script should not stop the template from
                // rendering, but the error must be visible in the output.
                eprintln!("  WARNING: <script> transpile failed: {e}");
                None
            }
        }
    };

    let bindings = script_result
        .as_ref()
        .map(ScriptBindings::from_result)
        .unwrap_or_default();

    let mut output = String::new();

    // Collect component references from HTML for imports
    let component_refs = collect_component_refs(&root, component_name);

    // Generated code is machine-written: silence lints the user cannot fix here.
    output.push_str("// @generated by uwebr — edits will be overwritten.\n");
    output.push_str("#![allow(unused_parens, unused_imports, dead_code, clippy::all)]\n\n");

    // Header
    output.push_str(
        "use uwebr_core::component::{Element, NodeType, PropValue, prop_string, prop_bool, prop_number};\n",
    );
    for comp in &component_refs {
        let mod_name = to_snake(comp);
        let fn_name = to_snake(comp);
        output.push_str(&format!(
            "use crate::generated::{mod_name}::{fn_name}_component;\n"
        ));
    }
    output.push('\n');

    // CSS as a const — `pub` so main.rs can pass it to App::with_css.
    if !css.is_empty() {
        output.push_str(&format!(
            "pub const CSS_{}: &str = r#\"{}\"#;\n\n",
            component_name.to_uppercase(),
            css
        ));
    }

    // Script output: state accessors + handler functions, at module scope.
    if let Some(ref result) = script_result {
        if !result.warnings.is_empty() {
            output.push_str("// JS transpile warnings:\n");
            for w in &result.warnings {
                output.push_str(&format!("//   {w}\n"));
            }
        }
        output.push_str("// Transpiled from <script> block:\n");
        output.push_str(&result.code);
        output.push('\n');
    } else if !script.is_empty() {
        output.push_str("// <script> block could not be transpiled:\n");
        for line in script.lines() {
            output.push_str(&format!("//   {line}\n"));
        }
        output.push('\n');
    }

    // Component function
    output.push_str(&format!(
        "pub fn {}_component(__props: &[(String, PropValue)]) -> Element {{\n",
        to_snake(component_name)
    ));
    output.push_str(&format!("    // HTML from {}.uwebr\n", component_name));

    // Event handlers are looked up by name at dispatch time, so they must be
    // (re-)registered on every render.
    let handlers = collect_event_handlers(&root, &bindings);
    for handler in &handlers {
        output.push_str(&format!(
            "    uwebr_core::events::register_action(\"{handler}\", {handler});\n"
        ));
    }

    output.push_str(&generate_element_code(&root, 2, &bindings));
    output.push_str("\n}\n");

    Ok(output)
}

/// Collect the distinct `on:*={handler}` names that resolve to script functions.
fn collect_event_handlers(node: &HtmlNode, bindings: &ScriptBindings) -> Vec<String> {
    let mut out = Vec::new();
    collect_event_handlers_into(node, bindings, &mut out);
    out
}

fn collect_event_handlers_into(node: &HtmlNode, bindings: &ScriptBindings, out: &mut Vec<String>) {
    let mut visit_attrs = |attrs: &[uwebr_html::ast::HtmlAttribute]| {
        for attr in attrs {
            if !attr.name.starts_with("on:") {
                continue;
            }
            if let Some(handler) = handler_name(&attr.value) {
                if bindings.is_function(&handler) && !out.contains(&handler) {
                    out.push(handler);
                }
            }
        }
    };

    match node {
        HtmlNode::Element(el) => {
            visit_attrs(&el.attributes);
            for child in &el.children {
                collect_event_handlers_into(child, bindings, out);
            }
        }
        HtmlNode::Component(comp) => {
            visit_attrs(&comp.attributes);
            for child in &comp.children {
                collect_event_handlers_into(child, bindings, out);
            }
        }
        HtmlNode::EachLoop(each) => {
            for child in &each.body {
                collect_event_handlers_into(child, bindings, out);
            }
        }
        HtmlNode::IfBlock(if_block) => {
            for child in &if_block.then_body {
                collect_event_handlers_into(child, bindings, out);
            }
            if let Some(else_body) = &if_block.else_body {
                for child in else_body {
                    collect_event_handlers_into(child, bindings, out);
                }
            }
        }
        HtmlNode::Fragment(nodes) => {
            for child in nodes {
                collect_event_handlers_into(child, bindings, out);
            }
        }
        _ => {}
    }
}

/// Extract the handler identifier from an event attribute value.
///
/// The HTML parser reports every attribute as a literal, so `on:click={inc}`
/// arrives as the string `"{inc}"`.
fn handler_name(value: &HtmlAttributeValue) -> Option<String> {
    let raw = match value {
        HtmlAttributeValue::Literal(v) => v.clone(),
        HtmlAttributeValue::Expression(v) | HtmlAttributeValue::Shorthand(v) => v.clone(),
        _ => return None,
    };
    let trimmed = raw.trim();
    let inner = trimmed
        .strip_prefix('{')
        .and_then(|s| s.strip_suffix('}'))
        .unwrap_or(trimmed)
        .trim();

    // Only plain identifiers can be registered as named actions.
    if inner.is_empty()
        || !inner.chars().all(|c| c.is_alphanumeric() || c == '_')
        || inner.chars().next().is_some_and(|c| c.is_numeric())
    {
        return None;
    }
    Some(inner.to_string())
}

/// Render one attribute as a `(name, PropValue)` tuple, or `None` to skip it.
fn generate_prop(
    attr: &uwebr_html::ast::HtmlAttribute,
    bindings: &ScriptBindings,
) -> Option<String> {
    // Event bindings become Closure props carrying the handler's name; the app
    // looks the name up in the action registry on click.
    if attr.name.starts_with("on:") {
        let handler = handler_name(&attr.value)?;
        return Some(format!(
            "(\"{}\".into(), PropValue::Closure(\"{}\".into()))",
            attr.name, handler
        ));
    }

    match &attr.value {
        HtmlAttributeValue::Literal(val) => Some(format!(
            "(\"{}\".into(), PropValue::String(\"{}\".into()))",
            attr.name,
            escape_rust_string(val)
        )),
        HtmlAttributeValue::Expression(expr) => Some(format!(
            "(\"{}\".into(), PropValue::String(({}).to_string()))",
            attr.name,
            bindings.rewrite_expr(expr)
        )),
        HtmlAttributeValue::Boolean(true) => {
            Some(format!("(\"{}\".into(), PropValue::Bool(true))", attr.name))
        }
        HtmlAttributeValue::Boolean(false) => None,
        HtmlAttributeValue::Shorthand(name) => Some(format!(
            "(\"{}\".into(), PropValue::String(({}).to_string()))",
            attr.name,
            bindings.rewrite_expr(name)
        )),
        HtmlAttributeValue::Conditional(cond, then_val, else_val) => Some(format!(
            "(\"{}\".into(), PropValue::String(if {} {{ \"{}\" }} else {{ \"{}\" }}.into()))",
            attr.name,
            bindings.rewrite_expr(cond),
            escape_rust_string(then_val),
            escape_rust_string(else_val)
        )),
    }
}

/// Escape a value for embedding in a Rust `"..."` literal.
fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

/// Does this node produce a value at all? Comments and raw HTML do not.
fn is_emittable(node: &HtmlNode) -> bool {
    match node {
        // Comments carry no runtime meaning.
        HtmlNode::Comment(_) => false,
        // {@html expr} needs a real HTML sub-parser; emitting a bare comment
        // line inside vec![] produced invalid Rust, so it is dropped for now.
        HtmlNode::RawHtml(_) => false,
        HtmlNode::Text(t) => !t.trim().is_empty(),
        HtmlNode::Fragment(nodes) => nodes.iter().any(is_emittable),
        _ => true,
    }
}

/// Generate Rust Element code from an HtmlNode
fn generate_element_code(node: &HtmlNode, indent: usize, bindings: &ScriptBindings) -> String {
    let pad = "    ".repeat(indent);
    match node {
        HtmlNode::Element(el) => {
            let tag = &el.tag;
            let props: Vec<String> = el
                .attributes
                .iter()
                .filter_map(|attr| generate_prop(attr, bindings))
                .collect();

            let emittable: Vec<&HtmlNode> =
                el.children.iter().filter(|c| is_emittable(c)).collect();

            let props_str = if props.is_empty() {
                "vec![]".to_string()
            } else {
                format!("vec![\n{}\n{}]", props.join(",\n"), pad)
            };

            // Check if any child is an each/if block (produces Vec<Element>)
            let has_dynamic = emittable
                .iter()
                .any(|c| matches!(c, HtmlNode::EachLoop(_) | HtmlNode::IfBlock(_)));

            let children_str = if emittable.is_empty() {
                "vec![]".to_string()
            } else if has_dynamic {
                // Mixed static + dynamic: build children imperatively
                let mut lines = vec!["{ let mut __c: Vec<Element> = vec![];".to_string()];
                for child in &emittable {
                    let code = generate_element_code(child, indent + 3, bindings)
                        .trim()
                        .to_string();
                    if matches!(child, HtmlNode::EachLoop(_) | HtmlNode::IfBlock(_)) {
                        lines.push(format!("__c.extend({});", code));
                    } else {
                        lines.push(format!("__c.push({});", code));
                    }
                }
                lines.push("__c }".to_string());
                lines.join("\n")
            } else {
                let children_code: Vec<String> = emittable
                    .iter()
                    .map(|c| generate_element_code(c, indent + 2, bindings))
                    .collect();
                format!("vec![\n{}\n{}]", children_code.join(",\n"), pad)
            };

            format!(
                "{}Element {{\n{}node_type: NodeType::Element(\"{}\".into()),\n{}props: {},\n{}children: {},\n{}}}",
                pad, pad, tag, pad, props_str, pad, children_str, pad
            )
        }
        HtmlNode::Text(text) => {
            format!(
                "{}Element {{ node_type: NodeType::Text(\"{}\".into()), props: vec![], children: vec![] }}",
                pad,
                escape_rust_string(text)
            )
        }
        HtmlNode::Expression(expr) => {
            format!(
                "{}Element {{ node_type: NodeType::Text(({}).to_string()), props: vec![], children: vec![] }}",
                pad,
                bindings.rewrite_expr(expr)
            )
        }
        HtmlNode::Fragment(nodes) => {
            let emittable: Vec<&HtmlNode> = nodes.iter().filter(|n| is_emittable(n)).collect();
            if emittable.is_empty() {
                return format!(
                    "{}Element {{ node_type: NodeType::Element(\"span\".into()), props: vec![], children: vec![] }}",
                    pad
                );
            }
            if emittable.len() == 1 {
                return generate_element_code(emittable[0], indent, bindings);
            }
            let children: Vec<String> = emittable
                .iter()
                .map(|n| generate_element_code(n, indent + 1, bindings))
                .collect();
            // `span`, not `div`: fragments come from mixed inline content like
            // `Count: {count}`, which must flow on one line rather than stack.
            format!(
                "{}Element {{\n{}node_type: NodeType::Element(\"span\".into()),\n{}props: vec![],\n{}children: vec![\n{}\n{}],\n{}}}",
                pad, pad, pad, pad, children.join(",\n"), pad, pad
            )
        }
        HtmlNode::Component(comp) => {
            let name = &comp.name;
            let props: Vec<String> = comp
                .attributes
                .iter()
                .filter_map(|attr| generate_prop(attr, bindings))
                .collect();
            let props_str = if props.is_empty() {
                "vec![]".to_string()
            } else {
                format!("vec![{}]", props.join(", "))
            };

            // Component composition: call the component function, passing any
            // props the caller wrote, then append any slot children supplied.
            let fn_name = format!("{}_component", to_snake(name));
            let call_args = if props.is_empty() {
                "&[]".to_string()
            } else {
                format!("&[{}]", props.join(", "))
            };
            let slot_children: Vec<String> = comp
                .children
                .iter()
                .filter(|c| is_emittable(c))
                .map(|c| generate_element_code(c, indent + 2, bindings))
                .collect();

            let children_str = if slot_children.is_empty() {
                format!("vec![{}({})]", fn_name, call_args)
            } else {
                format!(
                    "{{ let mut __c = vec![{}({})]; __c.extend(vec![\n{}\n{}]); __c }}",
                    fn_name,
                    call_args,
                    slot_children.join(",\n"),
                    pad
                )
            };

            format!(
                "{}Element {{\n{}node_type: NodeType::Component(\"{}\".into()),\n{}props: {},\n{}children: {},\n{}}}",
                pad, pad, name, pad, props_str, pad, children_str, pad
            )
        }
        HtmlNode::EachLoop(each) => {
            let item = &each.item_name;
            let iter = bindings.rewrite_expr(&each.iterable);
            let body_elements: Vec<String> = each
                .body
                .iter()
                .filter(|n| is_emittable(n))
                .map(|n| generate_element_code(n, indent + 3, bindings))
                .collect();
            let body_str = if body_elements.len() == 1 {
                body_elements[0].clone()
            } else {
                format!(
                    "vec![\n{}\n{}]",
                    body_elements.join(",\n"),
                    "    ".repeat(indent + 2)
                )
            };
            format!(
                "{}{}.iter().map(|{}| {{\n{}{}\n{}}}).collect::<Vec<_>>()",
                pad,
                iter,
                item,
                "    ".repeat(indent + 2),
                body_str.trim(),
                pad
            )
        }
        HtmlNode::IfBlock(if_block) => {
            let cond = bindings.rewrite_expr(&if_block.condition);
            let then_elements: Vec<String> = if_block
                .then_body
                .iter()
                .filter(|n| is_emittable(n))
                .map(|n| generate_element_code(n, indent + 2, bindings))
                .collect();
            let then_str = if then_elements.len() == 1 {
                then_elements[0].clone()
            } else {
                format!(
                    "vec![\n{}\n{}]",
                    then_elements.join(",\n"),
                    "    ".repeat(indent + 1)
                )
            };
            let else_str = if let Some(ref else_body) = if_block.else_body {
                let else_elements: Vec<String> = else_body
                    .iter()
                    .filter(|n| is_emittable(n))
                    .map(|n| generate_element_code(n, indent + 2, bindings))
                    .collect();
                if else_elements.len() == 1 {
                    format!(" else {{ {} }}", else_elements[0].trim())
                } else {
                    format!(
                        " else {{ vec![\n{}\n{}] }}",
                        else_elements.join(",\n"),
                        "    ".repeat(indent + 1)
                    )
                }
            } else {
                String::new()
            };
            format!(
                "{}if {} {{\n{}{}\n{}{}}}",
                pad,
                cond,
                "    ".repeat(indent + 1),
                then_str.trim(),
                pad,
                else_str
            )
        }
        // Filtered out by is_emittable before reaching here; kept for exhaustiveness.
        HtmlNode::RawHtml(_) | HtmlNode::Comment(_) => String::new(),
    }
}

/// Extract content between <tag>...</tag> blocks
pub fn extract_tag(content: &str, tag: &str) -> String {
    let mut result = String::new();
    let open = format!("<{}>", tag);
    let close = format!("</{}>", tag);

    let mut pos = 0;
    while let Some(start) = content[pos..].find(&open) {
        let start = pos + start + open.len();
        if let Some(end) = content[start..].find(&close) {
            result.push_str(&content[start..start + end]);
            pos = start + end + close.len();
        } else {
            break;
        }
    }

    result.trim().to_string()
}

/// Extract HTML content (everything except <style> and <script> blocks)
pub fn extract_html(content: &str) -> String {
    let mut result = content.to_string();

    // Remove <style>...</style>
    while let Some(start) = result.find("<style") {
        if let Some(tag_end) = result[start..].find('>') {
            let tag_end = start + tag_end + 1;
            if let Some(close_end) = result[tag_end..].find("</style>") {
                result = format!("{}{}", &result[..start], &result[tag_end + close_end + 8..]);
            } else {
                break;
            }
        } else {
            break;
        }
    }

    // Remove <script>...</script>
    while let Some(start) = result.find("<script") {
        if let Some(tag_end) = result[start..].find('>') {
            let tag_end = start + tag_end + 1;
            if let Some(close_end) = result[tag_end..].find("</script>") {
                result = format!("{}{}", &result[..start], &result[tag_end + close_end + 9..]);
            } else {
                break;
            }
        } else {
            break;
        }
    }

    result.trim().to_string()
}

/// Convert PascalCase or kebab-case to snake_case
pub fn to_snake(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            result.push('_');
        }
        if c == '-' || c == ' ' {
            result.push('_');
        } else {
            result.push(c.to_lowercase().next().unwrap_or(c));
        }
    }
    result
}

/// Collect PascalCase component names referenced in the HTML tree (excluding the root component itself)
fn collect_component_refs(node: &HtmlNode, root_name: &str) -> Vec<String> {
    let mut refs = Vec::new();
    collect_component_refs_into(node, root_name, &mut refs);
    refs
}

fn collect_component_refs_into(node: &HtmlNode, root_name: &str, refs: &mut Vec<String>) {
    match node {
        HtmlNode::Component(comp) => {
            if comp.name != root_name && !refs.contains(&comp.name) {
                refs.push(comp.name.clone());
            }
            for child in &comp.children {
                collect_component_refs_into(child, root_name, refs);
            }
        }
        HtmlNode::Element(el) => {
            for child in &el.children {
                collect_component_refs_into(child, root_name, refs);
            }
        }
        HtmlNode::Fragment(nodes) => {
            for child in nodes {
                collect_component_refs_into(child, root_name, refs);
            }
        }
        HtmlNode::EachLoop(each) => {
            for child in &each.body {
                collect_component_refs_into(child, root_name, refs);
            }
        }
        HtmlNode::IfBlock(ifnode) => {
            for child in &ifnode.then_body {
                collect_component_refs_into(child, root_name, refs);
            }
            if let Some(else_body) = &ifnode.else_body {
                for child in else_body {
                    collect_component_refs_into(child, root_name, refs);
                }
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_transpile_simple_element() {
        let html = r#"<div class="app"><h1>Hello</h1></div>"#;
        let result = transpile(html, "App").unwrap();
        assert!(result.contains("NodeType::Element(\"div\""));
        assert!(result.contains("NodeType::Element(\"h1\""));
        assert!(result.contains("NodeType::Text(\"Hello\""));
    }

    #[test]
    fn test_transpile_with_css() {
        let input = r#"<div class="box"><span>Hi</span></div>
<style>.box { width: 100px; }</style>"#;
        let result = transpile(input, "Box").unwrap();
        assert!(result.contains("CSS_BOX"));
        assert!(result.contains("width: 100px"));
    }

    #[test]
    fn test_transpile_with_script() {
        let input = r#"<div><p>Content</p></div>
<script>let x = 1;</script>"#;
        let result = transpile(input, "Page").unwrap();
        assert!(result.contains("Transpiled from"));
        assert!(!result.contains("// NOTE: Script transpilation requires"));
    }

    #[test]
    fn test_transpile_attributes() {
        let html = r#"<button id="btn" class="primary" disabled>Click</button>"#;
        let result = transpile(html, "Btn").unwrap();
        assert!(result.contains("id"));
        assert!(result.contains("btn"));
    }

    #[test]
    fn test_transpile_nested() {
        let html = r#"<div><div><span>Deep</span></div></div>"#;
        let result = transpile(html, "Nested").unwrap();
        assert!(result.contains("NodeType::Element(\"div\""));
        assert!(result.contains("NodeType::Element(\"span\""));
    }

    #[test]
    fn test_to_snake() {
        assert_eq!(to_snake("App"), "app");
        assert_eq!(to_snake("MyComponent"), "my_component");
        assert_eq!(to_snake("my-app"), "my_app");
        assert_eq!(to_snake("Button"), "button");
    }

    #[test]
    fn test_extract_tag() {
        let content =
            r#"Hello <style>.a { color: red; }</style> World <script>let x = 1;</script> End"#;
        let css = extract_tag(content, "style");
        assert_eq!(css, ".a { color: red; }");
        let js = extract_tag(content, "script");
        assert_eq!(js, "let x = 1;");
    }

    #[test]
    fn test_extract_html() {
        let content = r#"<div>Hi</div><style>.a{}</style><script>let x;</script>"#;
        let html = extract_html(content);
        assert_eq!(html, "<div>Hi</div>");
    }

    #[test]
    fn test_transpile_empty() {
        let result = transpile("", "Empty").unwrap();
        assert!(result.contains("pub fn empty_component(__props: &[(String, PropValue)])"));
    }

    #[test]
    fn test_transpile_component_function() {
        let html = r#"<div>Hello</div>"#;
        let result = transpile(html, "Hello").unwrap();
        assert!(result.contains("pub fn hello_component(__props: &[(String, PropValue)])"));
        assert!(result.contains("NodeType::Element(\"div\""));
        assert!(result.contains("NodeType::Text(\"Hello\""));
        assert!(!result.contains("pub fn main"));
    }

    #[test]
    fn test_transpile_each_loop() {
        let html = r#"<ul>{#each items as item}<li>{item}</li>{/each}</ul>"#;
        let result = transpile(html, "List").unwrap();
        assert!(
            result.contains("items.iter().map(|item|"),
            "Expected iterator"
        );
        assert!(result.contains("NodeType::Element(\"li\""));
        assert!(!result.contains("// TODO"));
    }

    #[test]
    fn test_transpile_if_block() {
        let html = r#"<div>{#if show}<span>Visible</span>{/if}</div>"#;
        let result = transpile(html, "Cond").unwrap();
        assert!(result.contains("if show"));
        assert!(result.contains("NodeType::Element(\"span\""));
        assert!(!result.contains("// TODO"));
    }

    #[test]
    fn test_transpile_if_else() {
        let html =
            r#"<div>{#if logged_in}<span>Welcome</span>{:else}<span>Login</span>{/if}</div>"#;
        let result = transpile(html, "Auth").unwrap();
        assert!(result.contains("if logged_in"));
        assert!(result.contains("Welcome"));
        assert!(result.contains("Login"));
    }

    #[test]
    fn test_transpile_mixed_children() {
        let html = r#"<div><h1>Title</h1>{#each items as item}<p>{item}</p>{/each}<footer>End</footer></div>"#;
        let result = transpile(html, "Mixed").unwrap();
        assert!(result.contains("items.iter().map(|item|"));
        assert!(result.contains("__c.extend("));
        assert!(result.contains("__c.push("));
    }

    #[test]
    fn test_transpile_component_composition() {
        let html = r#"<div><Header></Header><p>Content</p><Footer></Footer></div>"#;
        let result = transpile(html, "Page").unwrap();
        // Should generate use imports for referenced components
        assert!(result.contains("use crate::generated::header::header_component"));
        assert!(result.contains("use crate::generated::footer::footer_component"));
        // Should use NodeType::Component (not div wrapper)
        assert!(result.contains("NodeType::Component(\"Header\""));
        assert!(result.contains("NodeType::Component(\"Footer\""));
        // Should call component functions with props slice
        assert!(result.contains("header_component(&[])"));
        assert!(result.contains("footer_component(&[])"));
    }

    // ── Script ↔ template wiring (M6) ───────────────────────────

    #[test]
    fn test_script_state_not_emitted_at_module_scope() {
        // `let count = 0;` at module scope is not valid Rust; the scaffold used
        // to fail its very first `cargo build` because of this.
        let input = r#"<div><h1>Hi</h1></div>
<script>
  let count = 0;
  function increment() { count++; }
</script>"#;
        let result = transpile(input, "App").unwrap();
        for line in result.lines() {
            let t = line.trim_start();
            assert!(
                !(t.starts_with("let ") || t.starts_with("let mut ")),
                "module-scope let emitted: {line}"
            );
        }
    }

    #[test]
    fn test_script_state_becomes_accessors() {
        let input = r#"<div></div>
<script>let count = 0;</script>"#;
        let result = transpile(input, "App").unwrap();
        assert!(result.contains("fn __state_count()"));
        assert!(result.contains("fn __set_state_count("));
    }

    #[test]
    fn test_interpolation_reads_script_state() {
        let input = r#"<div><span>{count}</span></div>
<script>let count = 0;</script>"#;
        let result = transpile(input, "Counter").unwrap();
        assert!(
            result.contains("__state_count()"),
            "template must read the signal:\n{result}"
        );
    }

    #[test]
    fn test_interpolation_without_script_left_alone() {
        let html = r#"<div><span>{name}</span></div>"#;
        let result = transpile(html, "N").unwrap();
        assert!(result.contains("(name).to_string()"));
    }

    #[test]
    fn test_interpolation_in_expression_context() {
        let input = r#"<div>{count + 1}</div>
<script>let count = 0;</script>"#;
        let result = transpile(input, "C").unwrap();
        assert!(result.contains("__state_count() + 1"), "got:\n{result}");
    }

    #[test]
    fn test_click_handler_registered() {
        let input = r#"<button on:click={increment}>+</button>
<script>
  let count = 0;
  function increment() { count++; }
</script>"#;
        let result = transpile(input, "App").unwrap();
        assert!(
            result.contains("register_action(\"increment\", increment)"),
            "handler must be registered:\n{result}"
        );
    }

    #[test]
    fn test_click_handler_becomes_closure_prop() {
        let input = r#"<button on:click={increment}>+</button>
<script>function increment() {}</script>"#;
        let result = transpile(input, "App").unwrap();
        assert!(
            result.contains("PropValue::Closure(\"increment\".into())"),
            "got:\n{result}"
        );
    }

    #[test]
    fn test_unknown_handler_not_registered() {
        // No matching script function: nothing to bind, so do not emit a call
        // to an undefined symbol.
        let html = r#"<button on:click={missing}>+</button>"#;
        let result = transpile(html, "App").unwrap();
        assert!(!result.contains("register_action"));
    }

    #[test]
    fn test_handler_registered_once_for_repeated_use() {
        let input = r#"<div><button on:click={go}>a</button><button on:click={go}>b</button></div>
<script>function go() {}</script>"#;
        let result = transpile(input, "App").unwrap();
        assert_eq!(
            result.matches("register_action(\"go\"").count(),
            1,
            "duplicate registrations are pointless"
        );
    }

    #[test]
    fn test_comment_not_emitted_as_bare_line() {
        // A bare `// ...` inside vec![] produced invalid Rust.
        let html = "<div><!-- note --><span>Hi</span></div>";
        let result = transpile(html, "C").unwrap();
        assert!(result.contains("NodeType::Element(\"span\""));
        // No stray comment inside the children vec.
        assert!(!result.contains("vec![\n        //"));
    }

    #[test]
    fn test_raw_html_not_emitted_as_bare_line() {
        let html = "<div>{@html content}</div>";
        let result = transpile(html, "R").unwrap();
        assert!(
            !result.contains("// Raw HTML:"),
            "raw HTML must not leak a bare comment into vec![]:\n{result}"
        );
    }

    #[test]
    fn test_quotes_in_attribute_are_escaped() {
        let html = r#"<div title="say &quot;hi&quot;"></div>"#;
        let result = transpile(html, "Q").unwrap();
        // Must not terminate the Rust string literal early.
        assert!(!result.contains(r#"String("say "hi"")"#));
    }

    #[test]
    fn test_component_slot_children_preserved() {
        let html = r#"<div><Card><p>Slot</p></Card></div>"#;
        let result = transpile(html, "Page").unwrap();
        assert!(result.contains("card_component(&[])"));
        assert!(
            result.contains("NodeType::Element(\"p\""),
            "slot children must not be dropped:\n{result}"
        );
    }

    #[test]
    fn test_rewrite_expr_only_matches_whole_identifiers() {
        let bindings = ScriptBindings {
            states: vec!["count".to_string()],
            functions: vec![],
        };
        // `counter` must not be rewritten just because it starts with `count`.
        assert_eq!(bindings.rewrite_expr("counter"), "counter");
        assert_eq!(bindings.rewrite_expr("count"), "__state_count()");
        assert_eq!(
            bindings.rewrite_expr("count + count"),
            "__state_count() + __state_count()"
        );
    }

    #[test]
    fn test_handler_name_parsing() {
        assert_eq!(
            handler_name(&HtmlAttributeValue::Literal("{inc}".into())).as_deref(),
            Some("inc")
        );
        assert_eq!(
            handler_name(&HtmlAttributeValue::Literal("inc".into())).as_deref(),
            Some("inc")
        );
        assert_eq!(
            handler_name(&HtmlAttributeValue::Literal("{count + 1}".into())),
            None,
            "only plain identifiers can be named actions"
        );
    }

    #[test]
    fn test_scaffold_template_transpiles() {
        // The exact template `uwebr init` writes.
        let input = r#"<div class="app">
  <h1>Hello from uwebr!</h1>
</div>

<script>
  let count = 0;

  function increment() {
    count++;
  }
</script>

<style>
  .app { display: flex; background-color: #1a1a2e; color: #e0e0e0; }
  h1 { font-size: 2rem; }
</style>
"#;
        let result = transpile(input, "App").unwrap();
        assert!(result.contains("pub fn app_component(__props: &[(String, PropValue)])"));
        assert!(result.contains("CSS_APP"));
        assert!(result.contains("fn increment()"));
        assert!(result.contains("Hello from uwebr!"));
    }

    #[test]
    fn test_css_const_is_public() {
        // main.rs does `use generated::app::CSS_APP;`, which fails on a private const.
        let input = "<div></div>\n<style>.a { color: red; }</style>";
        let result = transpile(input, "App").unwrap();
        assert!(result.contains("pub const CSS_APP"));
    }

    #[test]
    fn test_generated_header_allows_lints() {
        // Generated code is not hand-editable; lint noise is pure distraction.
        let result = transpile("<div></div>", "App").unwrap();
        assert!(result.contains("@generated by uwebr"));
        assert!(result.contains("#![allow("));
    }

    #[test]
    fn test_mixed_inline_content_uses_span_wrapper() {
        // `Count: {count}` is inline text; a div wrapper would stack the parts
        // vertically because block tags default to a column flex.
        let input = "<p>Count: {count}</p>\n<script>let count = 0;</script>";
        let result = transpile(input, "C").unwrap();
        assert!(
            result.contains("NodeType::Element(\"span\""),
            "expected an inline wrapper:\n{result}"
        );
    }

    #[test]
    fn test_component_receives_props() {
        let input = r#"<div><Card title="Hello" count={42} /></div>
<script></script>
<style></style>"#;
        let result = transpile(input, "App").unwrap();
        assert!(
            result.contains("card_component(&["),
            "component with props must be called with a slice:\n{result}"
        );
        assert!(result.contains("PropValue::String(\"Hello\".into())"));
        assert!(
            result.contains("\"count\".into()"),
            "the count prop must be forwarded:\n{result}"
        );
    }

    #[test]
    fn test_component_no_props_uses_empty_slice() {
        let input = r#"<div><Card /></div>
<script></script>
<style></style>"#;
        let result = transpile(input, "App").unwrap();
        assert!(
            result.contains("card_component(&[])"),
            "propless component must be called with an empty slice:\n{result}"
        );
    }

    #[test]
    fn test_component_fn_signature_takes_props() {
        let result = transpile("<div></div>", "App").unwrap();
        assert!(result.contains("pub fn app_component(__props: &[(String, PropValue)])"));
    }

    #[test]
    fn test_generated_imports_prop_helpers() {
        let result = transpile("<div></div>", "App").unwrap();
        assert!(result.contains("prop_string"));
        assert!(result.contains("prop_bool"));
        assert!(result.contains("prop_number"));
    }
}
